Add keybinds for the garden
cookies-mod/mod pull request #208
Opened 2024-11-23 06:00 UTC by GrahamKracker

will need rebasing i think

2024-11-23 06:19 UTC, Morazzer requested changes
Looks fine to me, it may still be worth to add different possible options when the garden key binds are active. Like an option to only use them when holding a farming tool or smth like that

2024-11-23 06:19 UTC, Morazzer commented on src/main/java/codes/cookies/mod/config/ConfigManager.java
> +    public static void 	saveConfig(boolean createBackup, String reason) {
```suggestion
    public static void saveConfig(boolean createBackup, String reason) {
```

2024-11-23 06:19 UTC, Morazzer commented on src/main/java/codes/cookies/mod/config/categories/FarmingConfig.java
> +
Probably would be worth to move it upwards. Think this is a feature that shouldn't be buried at the bottom of the config.

2024-11-23 06:19 UTC, Morazzer commented on src/main/java/codes/cookies/mod/data/cookiesmoddata/CookiesModData.java
> +	{
```suggestion
	default void save() {
```

2024-11-23 06:19 UTC, Morazzer commented on src/main/java/codes/cookies/mod/data/farming/GardenKeybindsData.java
> +{
```suggestion
public class GardenKeybindsData implements CookiesModData, CodecJsonSerializable<Map<String, GardenKeybindsData.GardenKeyBindOverride>> {
```

2024-11-23 06:19 UTC, Morazzer commented on src/main/java/codes/cookies/mod/data/cookiesmoddata/CookieDataManager.java
> +	public static void save(CookiesModData modData) throws IOException {
Does this even throw an `IOException`? The `ExceptionHandler` should normally handle that

2024-11-23 06:19 UTC, Morazzer commented on src/main/java/codes/cookies/mod/data/cookiesmoddata/CookiesModData.java
> +	@SneakyThrows
Not required IF the throws is unnecessary

2024-11-23 06:41 UTC, GrahamKracker commented on src/main/java/codes/cookies/mod/config/categories/FarmingConfig.java
> +
![image](https://github.com/user-attachments/assets/48a13845-f3ea-47be-8da9-e8bd81be45f5)
moved to be just under pest warnings, available to see without scrolling

2024-11-23 17:12 UTC, Morazzer requested changes

2024-11-23 17:12 UTC, Morazzer commented on src/main/java/codes/cookies/mod/CookiesMod.java
> +			while(useGardenKeybinds.wasPressed() && LocationUtils.Island.GARDEN.isActive()) {
Why use a while here?

2024-11-23 17:12 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/keybinds/GardenKeybindPredicate.java
> +	HoldingFarmingTool("Holding Farming Tool", () -> {
Should be in snake case (and upper case)

2024-11-23 17:13 UTC, GrahamKracker commented on src/main/java/codes/cookies/mod/CookiesMod.java
> +			while(useGardenKeybinds.wasPressed() && LocationUtils.Island.GARDEN.isActive()) {
if you dont use that way to get input (thanks mojang) it would rapidly fire each tick making it hard to stop on the right one, you can test it out the other way if you like

2024-11-26 06:58 UTC, Morazzer approved these changes
Looks good, there are some formatting issues but I don't think it's worth requesting changes since it's mainly missing spaces

2024-11-26 06:59 UTC, merged