add visitor rare drop protection
cookies-mod/mod pull request #210
Opened 2024-11-25 15:16 UTC by GrahamKracker

needs testing

2024-11-26 08:14 UTC, zFlxw reviewed
Just one thing I noticed

2024-11-26 08:14 UTC, zFlxw commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		if(rejectButton.isEmpty() || !rejectButton.isOf(Items.RED_TERRACOTTA) || !visitorItemLore) {
In terms of consistency, there should be a null-check here as well
```suggestion
		if(rejectButton == null || rejectButton.isEmpty() || !rejectButton.isOf(Items.RED_TERRACOTTA) || !visitorItemLore) {
```

2024-11-28 06:58 UTC, Morazzer requested changes

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +	protected final ItemStack disabledItem = new ItemBuilder(Items.BARRIER).hideAdditionalTooltips().set(CookiesDataComponentTypes.ITEM_CLICK_RUNNABLE, Runnables.doNothing()).setName(Text.of("Refusing t
Maybe add some style to the text, as in make it non italic and red or smth

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		new java.util.Timer().schedule(
It may be better to use `CookiesMod#getExecutorService`

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		if(ConfigManager.getConfig().farmingConfig.visitorNotAsRareDropProtection.getValue()) {
```suggestion
		if (ConfigManager.getConfig().farmingConfig.visitorNotAsRareDropProtection.getValue()) {
```

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		if(visitorItem == null || visitorItem.isEmpty() || !visitorItem.isOf(Items.GREEN_TERRACOTTA) || !visitorItem.contains(DataComponentTypes.LORE)) {
```suggestion
		if (visitorItem == null || visitorItem.isEmpty() || !visitorItem.isOf(Items.GREEN_TERRACOTTA) || !visitorItem.contains(DataComponentTypes.LORE)) {
```

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +			"Pet Cake", //
Trailing comment

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		InventoryEvents.beforeInit("cookies-regex:.*", inv -> LocationUtils.Island.GARDEN.isActive() && ConfigManager.getConfig().farmingConfig.visitorRareDropProtection.getValue(), VisitorDropProtection::
May be worth adding something like `cookies-behaviour:always/never` or something in that direction

2024-11-28 06:58 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +	private void handleRejectButton(ItemStack rejectButton, boolean visitorItemLore) {
Maybe rename the parameters to fit their use a bit better
```suggestion
	private void handleRejectButton(ItemStack rejectStack, boolean applyProtection) {
```

2024-12-11 15:01 UTC, GrahamKracker commented
resolved https://github.com/cookies-mod/mod/pull/208#pullrequestreview-2460543792 too

2024-12-11 15:14 UTC, Morazzer requested changes

2024-12-11 15:14 UTC, Morazzer commented on src/main/generated/assets/cookies-mod/lang/en_us.json
> +  "cookies.config.farming.categories.visitors": "Visitors",
Duplicate key?

2024-12-11 15:14 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/GardenFeatures.java
> +		Loader.load("VisitorDropProtection", VisitorDropProtection::init);
```suggestion
		Loader.load("VisitorDropProtection", VisitorDropProtection::init);
```

2024-12-11 15:14 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +			.setName(Text.translatable(DROP_PROTECTION_MESSAGE).setStyle(Style.EMPTY.withColor(Formatting.RED).withItalic(false).withBold(true))).set(DataComponentTypes.RARITY, Rarity.COMMON).build();
Could be static I think? Also why is there a suppress warnings here?

2024-12-11 15:14 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		InventoryEvents.beforeInit("cookies-regex:.*", inv -> LocationUtils.Island.GARDEN.isActive() && ConfigManager.getConfig().farmingConfig.visitorRareDropProtection.getValue(), VisitorDropProtection::
```suggestion
		InventoryEvents.beforeInit("cookies-behaviour:always", inv -> LocationUtils.Island.GARDEN.isActive() && ConfigManager.getConfig().farmingConfig.visitorRareDropProtection.getValue(), VisitorDropProtection::new);
```

2024-12-11 15:14 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		if (!matcher.find()) {
Not sure but I think `String#matches` should work for this as well

2024-12-11 15:31 UTC, GrahamKracker commented on src/main/generated/assets/cookies-mod/lang/en_us.json
> +  "cookies.config.farming.categories.visitors": "Visitors",
wtf

2024-12-11 16:19 UTC, GrahamKracker commented on src/main/java/codes/cookies/mod/features/farming/garden/visitors/VisitorDropProtection.java
> +		if (!matcher.find()) {
this would require a match all at the start and end of the regex, is that still a better solution?

2024-12-15 10:51 UTC, Morazzer reviewed
Looks fine, will do some in game testing and merge if I don't find anything

2024-12-15 11:04 UTC, Morazzer approved these changes

2024-12-15 11:04 UTC, merged