Party commands and melody solver
cookies-mod/mod pull request #219
Opened 2024-12-23 18:36 UTC by GrahamKracker

2024-12-24 17:46 UTC, Morazzer requested changes

2024-12-24 17:46 UTC, Morazzer commented on src/main/java/codes/cookies/mod/utils/skyblock/PartyUtils.java
> +				request();
```suggestion
			if (LocationUtils.isInSkyblock()) {
				request();
			}
```

2024-12-24 17:46 UTC, Morazzer commented on src/main/java/codes/cookies/mod/utils/mixins/SlotMixin.java
> +	@Override
The indendation looks off

2024-12-24 17:46 UTC, Morazzer commented on src/main/java/codes/cookies/mod/mixins/KeybindingMixin.java
> +import codes.cookies.mod.CookiesMod;
```suggestion
```

2024-12-24 17:46 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/misc/PartyCommandsFeature.java
> +public class PartyCommandsFeature {
Applies to a lot of the class, wrong capitalization of field and method names

2024-12-24 17:46 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/misc/PartyCommandsFeature.java
> +            super(predicate, action);
```suggestion
        public DownTimeCommand(Supplier<Boolean> predicate) {
            super(predicate, null);
```

2024-12-24 17:46 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/dungeons/solver/terminals/MelodyTerminalSolver.java
> +            }
Maybe only set it to locked if the block prevent miss click option is on

2024-12-25 04:44 UTC, GrahamKracker commented on src/main/java/codes/cookies/mod/utils/mixins/SlotMixin.java
> +	@Override
i think thats github?

2024-12-25 04:45 UTC, GrahamKracker commented on src/main/java/codes/cookies/mod/features/dungeons/solver/terminals/MelodyTerminalSolver.java
> +            }
oh in all the testing we did it got removed :3

2024-12-26 08:51 UTC, Morazzer requested changes

2024-12-26 08:51 UTC, Morazzer commented on src/main/java/codes/cookies/mod/features/misc/PartyCommandsFeature.java
> +                if (Reason != null) {
Still wrong capitalization

2024-12-30 23:53 UTC, Morazzer reviewed
Looks fine to me, will do some testing tomorrow and merge if I don't find any problems!

2025-01-22 18:56 UTC, merged